USE [master]
GO

/****** Object:  Database [Movies]    Script Date: 12/1/2018 6:56:28 PM ******/
CREATE DATABASE [Movies]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Movies', FILENAME = N'C:\Users\kstar\Movies.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Movies_log', FILENAME = N'C:\Users\kstar\Movies_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Movies] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Movies].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Movies] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Movies] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Movies] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Movies] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Movies] SET ARITHABORT OFF 
GO

ALTER DATABASE [Movies] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Movies] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Movies] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Movies] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Movies] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Movies] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Movies] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Movies] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Movies] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Movies] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Movies] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Movies] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Movies] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Movies] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Movies] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Movies] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Movies] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Movies] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Movies] SET  MULTI_USER 
GO

ALTER DATABASE [Movies] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Movies] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Movies] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Movies] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Movies] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Movies] SET QUERY_STORE = OFF
GO

USE [Movies]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Movies] SET  READ_WRITE 
GO

